name: C++ with CMake with tests

on: [push, pull_request]

jobs:
  UniquePtrTests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: unique_ptr
    - name: mkdir build
      working-directory: homework/unique_ptr/
      run: mkdir build
    - name: Compile
      working-directory: homework/unique_ptr/build
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: homework/unique_ptr/build
      run: ctest -V
    - name: Run valgrind
      working-directory: homework/unique_ptr/build
      run: | 
        valgrind ./unique_ptr-ut
